get_filename_component(app_dir "${APP}" DIRECTORY)
get_filename_component(qt_root "${QT_DIR}/../../.." ABSOLUTE)
set(deploy_mode --release)
set(suffix "")
if(CONFIG STREQUAL "Debug")
  set(deploy_mode --debug)
  set(suffix d)
endif()
if(EXISTS "${qt_root}/bin/windeployqt.exe")
  execute_process(COMMAND "${qt_root}/bin/windeployqt.exe" ${deploy_mode} --no-translations --no-system-d3d-compiler --no-opengl-sw "${APP}" RESULT_VARIABLE code)
  if(NOT code EQUAL 0)
    message(FATAL_ERROR "Qt deployment failed: ${code}")
  endif()
else()
  foreach(module Core Gui Widgets Concurrent)
    file(COPY "${qt_root}/bin/Qt5${module}${suffix}.dll" DESTINATION "${app_dir}")
  endforeach()
  file(MAKE_DIRECTORY "${app_dir}/platforms")
  foreach(plugin qwindows qoffscreen)
    file(COPY "${qt_root}/plugins/platforms/${plugin}${suffix}.dll" DESTINATION "${app_dir}/platforms")
  endforeach()
endif()
get_filename_component(cv_bin "${CV_DIR}/../bin" ABSOLUTE)
foreach(module core imgproc imgcodecs calib3d features2d flann videoio)
  file(GLOB runtime "${cv_bin}/opencv_${module}[0-9]*${suffix}.dll")
  foreach(dll IN LISTS runtime)
    if(suffix OR NOT dll MATCHES "[0-9]d\\.dll$")
      file(COPY "${dll}" DESTINATION "${app_dir}")
    endif()
  endforeach()
endforeach()
if(HIK_ENABLED AND EXISTS "${HIK_RUNTIME}")
  file(GLOB runtime "${HIK_RUNTIME}/*.dll")
  file(COPY ${runtime} DESTINATION "${app_dir}")
endif()
# Qt's development subset can lack deployment tools. Include the compiler CRT
# from its redistributable tree, never from an unrelated project's binaries.
if(NOT suffix)
  file(GLOB crt_dirs "$ENV{VCToolsRedistDir}/x64/Microsoft.VC*.CRT")
  foreach(crt IN LISTS crt_dirs)
    file(GLOB runtime "${crt}/*.dll")
    if(runtime)
      file(COPY ${runtime} DESTINATION "${app_dir}")
    endif()
  endforeach()
endif()
