set(MLLM_ENVIRONMENT_FILE "${CMAKE_CURRENT_LIST_DIR}/../config/environment.ini" CACHE FILEPATH "Local dependency paths")
if(NOT EXISTS "${MLLM_ENVIRONMENT_FILE}")
  message(FATAL_ERROR "Copy config/defaults/environment.ini to config/environment.ini and set dependency paths.")
endif()
file(STRINGS "${MLLM_ENVIRONMENT_FILE}" env_lines ENCODING UTF-8)
foreach(line IN LISTS env_lines)
  if(line MATCHES "^([A-Za-z0-9_]+)=(.+)$")
    set(key "${CMAKE_MATCH_1}")
    set(value "${CMAKE_MATCH_2}")
    if(key MATCHES "^(Qt5_DIR|OpenCV_DIR|CMAKE_MAKE_PROGRAM|HIK_MVS_ROOT|HIK_MVS_RUNTIME_DIR|MLLM_ENABLE_HIK|MLLM_MSVC_INCLUDE_PREFIX)$")
      set(${key} "${value}" CACHE STRING "MLLM local environment" FORCE)
    endif()
  endif()
endforeach()
